import type { Metadata } from "next"

import "./globals.css"
import { Viaoda_Libre, Roboto } from "next/font/google"
import Footer from "@/components/Footer"

const viaodaLibre = Viaoda_Libre({ weight: ["400"], subsets: ["latin"] })
const roboto = Roboto({ subsets: ["cyrillic"], weight: ["400"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
